version: "3.8"

services:
  tube-archivist-processor:
    image: ghcr.io/peppy6582/tube-archivist-processor:latest
    container_name: tube_archivist_processor
    environment:
      VIDEO_DIRECTORY: "/TubeArchivist/YouTube/"
      CHANNELS_DIRECTORY: "/TubeArchivist/YouTubeChannels/"
      PROCESSED_FILES_TRACKER: "processed_files.txt"
      YOUTUBE_API_KEY: "${YOUTUBE_API_KEY}"
      APPRISE_URL: "${APPRISE_URL}"
      CHANNELS_DVR_API_REFRESH_URL: "${CHANNELS_DVR_API_REFRESH_URL}"
    volumes:
      - ./YouTube:/TubeArchivist/YouTube
      - ./YouTubeChannels:/TubeArchivist/YouTubeChannels
      - ./processed_files.txt:/app/processed_files.txt
    restart: unless-stopped
